/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniprojet;

import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Walid
 */
public class CreateAccountPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoginPanel
     */
    public CreateAccountPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomInscriptionET = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        emailInscriptionET = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        passwordInscriptionET = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(36, 47, 65));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Mot de passe");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Nom complet");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel3.setBackground(new java.awt.Color(204, 204, 204));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Email");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        nomInscriptionET.setBackground(new java.awt.Color(36, 47, 65));
        nomInscriptionET.setForeground(new java.awt.Color(255, 255, 255));
        nomInscriptionET.setText("Nom et prénom");
        nomInscriptionET.setBorder(null);
        nomInscriptionET.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomInscriptionETMouseClicked(evt);
            }
        });
        add(nomInscriptionET, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 200, 20));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 200, 10));

        emailInscriptionET.setBackground(new java.awt.Color(36, 47, 65));
        emailInscriptionET.setForeground(new java.awt.Color(255, 255, 255));
        emailInscriptionET.setText("Adresse mail");
        emailInscriptionET.setBorder(null);
        emailInscriptionET.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                emailInscriptionETFocusGained(evt);
            }
        });
        add(emailInscriptionET, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 200, 20));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 200, -1));

        passwordInscriptionET.setBackground(new java.awt.Color(36, 47, 65));
        passwordInscriptionET.setForeground(new java.awt.Color(255, 255, 255));
        passwordInscriptionET.setText("jPasswordField1");
        passwordInscriptionET.setBorder(null);
        passwordInscriptionET.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordInscriptionETFocusGained(evt);
            }
        });
        add(passwordInscriptionET, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 200, 20));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 200, 10));

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel5.setForeground(new java.awt.Color(36, 47, 65));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Créer Compte");
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel5, java.awt.BorderLayout.CENTER);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 130, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Création Compte Administrateur");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void emailInscriptionETFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailInscriptionETFocusGained
        emailInscriptionET.setText("");
    }//GEN-LAST:event_emailInscriptionETFocusGained

    private void passwordInscriptionETFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordInscriptionETFocusGained
        passwordInscriptionET.setText("");
    }//GEN-LAST:event_passwordInscriptionETFocusGained

    private void nomInscriptionETMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomInscriptionETMouseClicked
        nomInscriptionET.setText("");
    }//GEN-LAST:event_nomInscriptionETMouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
            if(nomInscriptionET.getText().length()==0)  // Checking for empty field
            JOptionPane.showMessageDialog(null, "Entrez un nom");
            else if(emailInscriptionET.getText().length()==0)
            JOptionPane.showMessageDialog(null, "Entrez un email");    
            else if(passwordInscriptionET.getPassword().length==0)  // Checking for empty field
            JOptionPane.showMessageDialog(null, "Entrez un mot de passe");
            else{
            String mail = emailInscriptionET.getText();   // Collecting the input
            String nom = nomInscriptionET.getText();   // Collecting the input
            char[] pass = passwordInscriptionET.getPassword(); // Collecting the input
            String pwd = String.copyValueOf(pass);  // converting from array to string
            if(validate_signup(nom,mail,pwd)){
            JOptionPane.showMessageDialog(null, "Inscription réussite");
            }
            else{
            JOptionPane.showMessageDialog(null, "Erreur");}
            }
    }//GEN-LAST:event_jLabel5MouseClicked

        private boolean validate_signup(String nom,String email,String password) {
    try{           
       Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
       java.sql.Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:1527/java?" + "user=root&password=");     
       java.sql.PreparedStatement pst = conn.prepareStatement("Insert into user (nom,email,password) values (?,?,?)");
       pst.setString(1, nom); 
       pst.setString(2, email); 
       pst.setString(3, password);
       int n = pst.executeUpdate();                        
       if (n != 0) {
           return true;
       } else {
           return false;
       }
    }
    catch(Exception e){
        e.printStackTrace();
        return false;
        }       
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailInscriptionET;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField nomInscriptionET;
    private javax.swing.JPasswordField passwordInscriptionET;
    // End of variables declaration//GEN-END:variables
}
