/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package miniprojet;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import java.sql.DriverManager;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author Walid
 */
public class LoginPanel extends javax.swing.JPanel {
    /**
     * Creates new form LoginPanel
     */
    public LoginPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        emailLoginET = new javax.swing.JTextField();
        passwordLoginET = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        adminCheckBox = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(36, 47, 65));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("Connectez-vous à votre compte");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Mot de passe");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Email");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        emailLoginET.setBackground(new java.awt.Color(36, 47, 65));
        emailLoginET.setForeground(new java.awt.Color(255, 255, 255));
        emailLoginET.setText("Votre adresse mail");
        emailLoginET.setBorder(null);
        emailLoginET.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                emailLoginETMouseClicked(evt);
            }
        });
        add(emailLoginET, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 200, 20));

        passwordLoginET.setBackground(new java.awt.Color(36, 47, 65));
        passwordLoginET.setForeground(new java.awt.Color(255, 255, 255));
        passwordLoginET.setText("jPasswordField1");
        passwordLoginET.setBorder(null);
        passwordLoginET.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                passwordLoginETFocusGained(evt);
            }
        });
        add(passwordLoginET, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 200, 20));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 200, 10));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 200, 10));

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel4.setForeground(new java.awt.Color(36, 47, 65));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Connexion");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel4, java.awt.BorderLayout.CENTER);

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, 130, 30));

        adminCheckBox.setBackground(new java.awt.Color(36, 47, 65));
        adminCheckBox.setForeground(new java.awt.Color(255, 255, 255));
        adminCheckBox.setText("Je suis un admin");
        adminCheckBox.setBorder(null);
        adminCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminCheckBoxActionPerformed(evt);
            }
        });
        add(adminCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 280, 140, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void adminCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminCheckBoxActionPerformed

    private void passwordLoginETFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_passwordLoginETFocusGained
        passwordLoginET.setText("");
    }//GEN-LAST:event_passwordLoginETFocusGained

    private void emailLoginETMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailLoginETMouseClicked
        emailLoginET.setText("");
    }//GEN-LAST:event_emailLoginETMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
            if(emailLoginET.getText().length()==0)  // Checking for empty field
            JOptionPane.showMessageDialog(null, "Entrez un email");
            else if(passwordLoginET.getPassword().length==0)  // Checking for empty field
            JOptionPane.showMessageDialog(null, "Entrez un mot de passe");
            else{
            String mail = emailLoginET.getText();   // Collecting the input
            char[] pass = passwordLoginET.getPassword(); // Collecting the input
            String pwd = String.copyValueOf(pass);  // converting from array to string
            if(validate_login(mail,pwd)){
            //JOptionPane.showMessageDialog(null, "Correct Login Credentials");
            if (adminCheckBox.isSelected()){
            JFrame frame = new JFrame ("Admin Panel");
            frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
            frame.getContentPane().add (new AdminPanel());
            frame.setSize(750,480);
            frame.setVisible (true);}
            else{
            JFrame frame = new JFrame ("Client Panel");
            frame.setDefaultCloseOperation (JFrame.EXIT_ON_CLOSE);
            frame.getContentPane().add(new GoogleMaps());
            //frame.setSize(630,600);
            frame.setVisible (true);
            }
            }
            else{
            JOptionPane.showMessageDialog(null, "Mauvais coordonnées");}
            }        
    }//GEN-LAST:event_jLabel4MouseClicked

    private boolean validate_login(String email,String password) {
    try{           
       Class.forName("com.mysql.jdbc.Driver");  // MySQL database connection
       java.sql.Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:1527/java?" + "user=root&password=");     
       java.sql.PreparedStatement pst = conn.prepareStatement("Select * from user where email=? and password=?");
       pst.setString(1, email); 
       pst.setString(2, password);
       ResultSet rs = pst.executeQuery();                        
       if(rs.next())            
           return true;    
       else
           return false;            
    }
    catch(Exception e){
        e.printStackTrace();
        return false;
        }       
    }
    private void jLabel4ActionPerformed(java.awt.event.ActionEvent evt){
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox adminCheckBox;
    private javax.swing.JTextField emailLoginET;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPasswordField passwordLoginET;
    // End of variables declaration//GEN-END:variables
}
